[build]
publish = "exampleSite/public"
command = 'cd exampleSite && echo -e "\ngoogleAnalytics: $GOOGLE_ANALYTICS \ndisqusShortname: $DISQUS_SHORTNAME \n" >> config.yaml && npx --yes --package=hugo-bin@0.163.0 -- hugo --gc --minify --themesDir ../..'

[context.production.environment]
HUGO_VERSION = "0.143.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
HUGO_THEME = "hugo-profile-master"

[context.split1]
command = "cd exampleSite && npx --yes --package=hugo-bin@0.163.0 -- hugo --gc --minify --enableGitInfo --themesDir ../.."

[context.split1.environment]
HUGO_VERSION = "0.143.0"
HUGO_ENV = "production"
HUGO_THEME = "hugo-profile-master"

[context.deploy-preview]
command = "cd exampleSite && npx --yes --package=hugo-bin@0.163.0 -- hugo --gc --minify --buildFuture --themesDir ../.. -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.143.0"
HUGO_THEME = "hugo-profile-master"

[context.branch-deploy]
command = "cd exampleSite && npx --yes --package=hugo-bin@0.163.0 -- hugo --gc --minify --themesDir ../.. -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.143.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
