[build]
publish = "exampleSite/public"
command = 'cd exampleSite && echo -e "\ngoogleAnalytics: $GOOGLE_ANALYTICS \ndisqusShortname: $DISQUS_SHORTNAME \n" >> config.yaml && hugo --gc --minify --themesDir ../.. --theme hugo-profile-master'

[context.production.environment]
HUGO_VERSION = "0.143.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "cd exampleSite && hugo --gc --minify --enableGitInfo --themesDir ../.. --theme hugo-profile-master"

[context.split1.environment]
HUGO_VERSION = "0.143.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "cd exampleSite && hugo --gc --minify --buildFuture --themesDir ../.. --theme hugo-profile-master -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.143.0"

[context.branch-deploy]
command = "cd exampleSite && hugo --gc --minify --themesDir ../.. --theme hugo-profile-master -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.143.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
